name: Prodshop theme
type: theme
base theme: stark
description: A flexible theme.
package: Custom
core_version_requirement: ^10 || ^11
libraries:
  - prodshop_theme/global
  - prodshop_theme/tailwindcss
regions:
  header: 'Header'
  primary_menu: 'Primary menu'
  secondary_menu: 'Secondary menu'
  page_top: 'Page top'
  page_bottom: 'Page bottom'
  featured: 'Featured'
  breadcrumb: 'Breadcrumb'
  content: 'Content'
  sidebar_first: 'Sidebar first'
  sidebar_second: 'Sidebar second'
  footer: 'Footer'
