# Main theme library.
global:
  js:
    js/prodshop-theme.js: {}
  dependencies:
    - core/drupal
  css:
    base:
      css/base/elements.css: {}
    component:
      css/component/block.css: {}
      css/component/breadcrumb.css: {}
      css/component/field.css: {}
      css/component/form.css: {}
      css/component/header.css: {}
      css/component/menu.css: {}
      css/component/messages.css: {}
      css/component/node.css: {}
      css/component/sidebar.css: {}
      css/component/table.css: {}
      css/component/tabs.css: {}
      css/component/buttons.css: {}
    layout:
      css/layout/layout.css: {}
    theme:
      css/theme/print.css: { media: print }
tailwindcss:
  js:
    https://cdn.tailwindcss.com: { type: external, minified: true, weight: -10 }
source_sans:
  css:
    component:
      //fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap: { type: external }
playfair_display:
  css:
    component:
      //fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap: { type: external }
